### PR TITLE
Mark Reminduck as EOL

### PR DESCRIPTION
**Pull request by ghost**
> This application is no longer maintained.

Source: https://github.com/matfantinel/reminduck/

### CODE REVIEW

**Comment by ghost** [comment]
@bbhtt How can I fix the following issue:

> "finish-args-unnecessary-xdg-config-autostart-create-access"

**Comment by bbhtt** [comment]
Needs an exception to the linter.

**Comment by ghost** [comment]
> Needs an exception to the linter.

https://github.com/flathub-infra/flatpak-builder-lint/pull/541

**Comment by ghost** [comment]
@bbhtt Reminduck is ready to be marked as EOL.

@matfantinel FYI.

**Pull request merged**
