### PR TITLE
Bump runtime to 22.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
cc @matfantinel any idea if this permission is necessary?

https://github.com/flathub/com.github.matfantinel.reminduck/blob/d73e6eb808d5b54c1ded41d8eeb7c20a7436fbe6/com.github.matfantinel.reminduck.json#L14

**Comment by matfantinel** [comment]
@bbhtt If I recall correctly, that was needed to have Reminduck auto-start after a reboot, so reminders wouldn't be lost if the user forgot to open the app. I am not aware if that permission is no longer needed or changed names

**Comment by bbhtt** [comment]
> @bbhtt If I recall correctly, that was needed to have Reminduck auto-start after a reboot, so reminders wouldn't be lost if the user forgot to open the app. I am not aware if that permission is no longer needed or changed names

You might want to make a PR to add an exception then. Similar to this https://github.com/flathub/flatpak-builder-lint/blob/cef445c34e7473faa46c33e698d173c4ad1f2822/flatpak_builder_lint/staticfiles/exceptions.json#L1533

**Comment by bbhtt** [comment]
The permanent solution is adding support for the autostart portal in the long run https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Background

**Comment by matfantinel** [comment]
For the record, this app is currently unmaintained as I don't use it (nor Linux) anymore. I'd be happy to approve/merge PRs but likely won't be able to change and test those new settings

**Pull request closed without merging**
